image: alpine:latest

stages:
  - build

build:
  tags:
    - myusine
  stage: build
  script:
    - echo "BUILD !!!"

prod:
  tags:
    - myusine
  stage: deploy
  script:
    - echo "kubectl apply -t deply.yml"
  rules:
    - if: $CI_COMMIT_TAG